apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-behavior
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30 
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
